services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      - APP_URL=${APP_URL}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - storage_data:/app/storage
      - cache_data:/app/bootstrap/cache
      - uploads_data:/app/public/uploads
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.4
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD='true'
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
  storage_data:
  cache_data:
  uploads_data:
